### ISSUE TITLE
Not all UI Working (Edited: Most not Working)

### ISSUE THREAD

**Issue by peltonmonster17** [grimmtusk/MHFU-HD#1]
Button prompts work beautifully, but for some weird reason the items remain unchanged. File structure is fine, and the items.png file is there, so I don't know what the problem could be.

**Comment by peltonmonster17** [comment]
So I've done some digging. Not only do the items not work - none of the intro png's work. I had to mess around with ppsspp, but it seems like the hashes in the textures.ini don't match up to my game. And even after manually changing the hashes, the images are cropped off in game. 

Good news though - the UI during gameplay is working great.

**Comment by HadariLiadon** [comment]
same as the pelton monster, i think that the codes for the textures are maybe wrong bcs i'm using the ulus10391 version and just the buttons work but items don't

**Comment by grimmtusk** [comment]
I run ULUS10391 and these hashes work for me. I have no idea why they don't for you, but know this is just a project that I did for myself, they're not meant to be a public project on which I keep improving, I just put them here for safe keeping and for sharing with a few friends. I just made them because I was bored and I was playing a lot of MHFU at the time. I'm not playing anymore and have no real use or need to continue working on this. As a suggestion just enable texture saving to get your own file's hashes and replace with my files. It's tedious but that's what I did in the first place as well, at least you won't need to do any actual graphics. Good luck!
